// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cub;

#nullable disable

namespace cub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250412173806_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cub.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("PULocationID")
                        .HasColumnType("int");

                    b.Property<float?>("fare_amount")
                        .HasColumnType("real");

                    b.Property<int?>("passenger_count")
                        .HasColumnType("int");

                    b.Property<int?>("store_and_fwd_flag")
                        .HasColumnType("int");

                    b.Property<float?>("tip_amount")
                        .HasColumnType("real");

                    b.Property<string>("tpep_dropoff_datetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tpep_pickup_datetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("trip_distance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
