// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cub;

#nullable disable

namespace cub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<float>("fare_amount")
                        .HasColumnType("real");

                    b.Property<int?>("passenger_count")
                        .HasColumnType("int");

                    b.Property<int?>("store_and_fwd_flag")
                        .HasColumnType("int");

                    b.Property<float?>("tip_amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("tpep_dropoff_datetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tpep_pickup_datetime")
                        .HasColumnType("datetime2");

                    b.Property<float>("trip_distance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
